version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
