# Generated by Django 4.0 on 2022-01-27 02:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='acrobatics',
        ),
        migrations.RemoveField(
            model_name='character',
            name='animalHandling',
        ),
        migrations.RemoveField(
            model_name='character',
            name='arcana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='atheletics',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='deception',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='history',
        ),
        migrations.RemoveField(
            model_name='character',
            name='insight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intimidation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='character',
            name='perception',
        ),
        migrations.RemoveField(
            model_name='character',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='persuasion',
        ),
        migrations.RemoveField(
            model_name='character',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sleightOfHand',
        ),
        migrations.RemoveField(
            model_name='character',
            name='stealth',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='survival',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.JSONField(default=api.models.abilities_default),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.JSONField(default=api.models.skills_default),
        ),
    ]
