# Generated by Django 4.0 on 2022-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_character_acrobatics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='maxHp',
            field=models.IntegerField(default=0),
        ),
    ]
