# Generated by Django 4.0 on 2022-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
