# Generated by Django 4.0 on 2022-02-03 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_character_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
