# Generated by Django 4.0 on 2022-02-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_character_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='_class',
            field=models.CharField(choices=[['none', 'None'], ['barbarian', 'Barbarian'], ['bard', 'Bard'], ['cleric', 'Cleric'], ['druid', 'Druid'], ['fighter', 'Fighter'], ['monk', 'Monk'], ['paladin', 'Paladin'], ['ranger', 'Ranger'], ['rogue', 'Rogue'], ['sorcerer', 'Sorcerer'], ['warlock', 'Warlock'], ['wizard', 'Wizard'], ['artificer', 'Artificer'], ['bloodHunter', 'Blood Hunter']], max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[['none', 'None'], ['dragonborn', 'Dragonborn'], ['dwarf', 'Bard'], ['elf', 'Cleric'], ['gnome', 'Druid'], ['half-elf', 'Fighter'], ['halfling', 'Monk'], ['half-orc', 'Paladin'], ['human', 'Ranger'], ['tiefling', 'Rogue']], max_length=64),
        ),
    ]
