# Generated by Django 4.0 on 2022-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='_class',
            field=models.CharField(choices=[['', 'None'], ['barbarian', 'Barbarian'], ['bard', 'Bard'], ['cleric', 'Cleric'], ['druid', 'Druid'], ['fighter', 'Fighter'], ['monk', 'Monk'], ['paladin', 'Paladin'], ['ranger', 'Ranger'], ['rogue', 'Rogue'], ['sorcerer', 'Sorcerer'], ['warlock', 'Warlock'], ['wizard', 'Wizard'], ['artificer', 'Artificer'], ['bloodHunter', 'Blood Hunter']], max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[['', 'None'], ['dragonborn', 'Dragonborn'], ['dwarf', 'Dwarf'], ['elf', 'Elf'], ['gnome', 'Gnome'], ['half-elf', 'Half-Elf'], ['halfling', 'Halfling'], ['half-orc', 'Half-Orc'], ['human', 'Human'], ['tiefling', 'Tiefling']], max_length=64),
        ),
    ]
