runtime: python37

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto

env_variables:
  POSTGRESQL_CONNECTION_NAME: project:region:db
  POSTGRES_DB: [DB NAME]
  POSTGRES_PASSWORD: [DB PASSWORD]
  POSTGRES_USER: [DB USER]
  POSTGRES_HOST: [DB HOST]
