runtime: python39

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto

env_variables:
  APPENGINE_URL: https://django-app-340805.uc.r.appspot.com
  # POSTGRESQL_CONNECTION_NAME: project:region:db
  # POSTGRES_DB: [DB NAME]
  # POSTGRES_PASSWORD: [DB PASSWORD]
  # POSTGRES_USER: [DB USER]
  # POSTGRES_HOST: [DB HOST]
